### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by aiturralde** [ANDRESI-Training/Ferguson#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by michaelpeele** [comment]
Please add me

**Comment by Clairefox** [comment]
Hello!

**Comment by bainese** [comment]
Good morning

**Comment by AJDataDev** [comment]
Hi all

**Comment by Jiminy0012** [comment]
Hi

**Comment by Taylorjh** [comment]
hello

**Comment by chandra151969** [comment]
Please add me as a collaborator.

**Comment by WesSummers** [comment]
I would like to be4 added.

**Comment by bbrown127** [comment]
Please add me

**Comment by pramodps13** [comment]
hello

**Comment by cblairevans** [comment]
my comment.

**Comment by BlairEvans** [comment]
found my recovery codes!

**Comment by rrockwood** [comment]
ok, found the right place now, thanks
